package request_state

const ( 
	PENDING = "PENDING" 
	PROCESS = "PROCESS" 
	FAILED = "FAILED" 
	SUCCES = "SUCCES" 
	STORED = "STORED"
	RESTORED = "RESTORED"
	DELETED = "DELETED"
	NOT_FOUND = "NOT FOUND"
)